### ISSUE TITLE
Chart Selection - Doc Update Needed

### ISSUE THREAD

**Issue by LanceMcCarthy** [telerik/uwp-docs#56]
Due to a performance optimization included in newer version of UI for UWP Chart, the selection documentation needs an update to address the need to include the following approach:

```C#
public class MyContainerVisualFactory : ContainerVisualsFactory
{
    protected override bool CanDrawContainerVisual(PresenterBase visualElement)
    {
        return false;
    }
}
```

```XML
<telerikChart:RadCartesianChart.ContainerVisualsFactory>
   <local:MyContainerVisualFactory/>
</telerikChart:RadCartesianChart.ContainerVisualsFactory>
```

Currently, in 2018.3.911, selection will not occur without this override.

**Comment by LanceMcCarthy** [comment]
@APopatanasov Is this something we're going to take care of internally (i.e. in the selection behavior) or should I add this to the Selection documentation article

**Comment by APopatanasov** [comment]
@LanceMcCarthy This is a limitation caused by the composition API or least I believe currently we should treat it as a limitation. I don't think soon we will be able to address it. Great job with the updated article. 

The Composition API has been boosted a lot since the April's update and I hope one day I will be able to return to the changes we have made in the chart and to rewrite some of the ugly code that has been left there. 😄
